# Generated by Django 6.0.4 on 2026-04-16 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0004_initial'),
        ('common', '0003_initial'),
        ('merchant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplier',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='common.country'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='suppliers', to='merchant.merchant'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='suppliers', to='branch.tag'),
        ),
        migrations.AddField(
            model_name='suppliercommission',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='merchant.supplier'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='commission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='merchant.suppliercommission'),
        ),
        migrations.AddField(
            model_name='suppliervariant',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='supplier_variants', to='common.category'),
        ),
        migrations.AddField(
            model_name='suppliervariant',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.supplier'),
        ),
        migrations.AddField(
            model_name='suppliervariant',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='supplier_variants', to='common.variant'),
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('name', 'country')},
        ),
        migrations.AddConstraint(
            model_name='suppliervariant',
            constraint=models.UniqueConstraint(fields=('supplier', 'category', 'variant'), name='unique_variant_per_supplier_per_category'),
        ),
    ]
