# Generated by Django 6.0.4 on 2026-04-16 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0003_initial'),
        ('customer', '0001_initial'),
        ('order', '0001_initial'),
        ('parcel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerdevice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='customer.customer'),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='customer.customer'),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.gateway'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='order.order'),
        ),
        migrations.AddField(
            model_name='payment',
            name='parcel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='parcel.parcel'),
        ),
        migrations.AddIndex(
            model_name='customerdevice',
            index=models.Index(fields=['fcm'], name='customer_cu_fcm_17e994_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('reference__isnull', True), _negated=True), fields=('reference',), name='unique_non_null_reference'),
        ),
    ]
