# Generated by Django 6.0.4 on 2026-04-16 00:18

import common.models.catalog.category
import common.models.catalog.item
import common.models.service
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('timezone', models.CharField(choices=[('Africa/Kinshasa', 'Africa/Kinshasa')], max_length=100, null=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('small_order_threshold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('small_order_fee', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('service_fee_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_fee_cap_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_radius', models.FloatField(default=3, help_text='in kilometers')),
                ('delivery_fee_base_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_fee_cap_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_fee_cpm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_fee_cpk', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debt_cap', models.DecimalField(decimal_places=2, default=3000.0, help_text='Courier maximum dept', max_digits=10)),
                ('bbox', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=4)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='CityService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['service__index'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('cd', 'CD')], help_text='lowerecase ISO 3166-1 alpha-2 country code', max_length=2, unique=True)),
                ('dial_code', models.CharField(max_length=3, unique=True)),
                ('smallest_bill', models.PositiveSmallIntegerField()),
                ('currency', models.CharField(choices=[('cdf', 'CDF')], help_text='ISO 4217 currency code', max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('cdf', 'CDF')], max_length=3, null=True)),
                ('name', models.CharField(choices=[('m-pesa', 'M-Pesa'), ('airtel-money', 'Airtel Money'), ('orange-money', 'Orange Money')], max_length=20)),
                ('min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GatewayRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fixed_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percent_fee', models.DecimalField(decimal_places=3, max_digits=4)),
            ],
            options={
                'ordering': ['gateway', 'min', 'max'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('index', models.PositiveSmallIntegerField(default=0)),
                ('image', models.ImageField(blank=True, max_length=150, null=True, upload_to=common.models.catalog.item.Item.upload_image)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True)),
                ('usage', models.CharField(blank=True, max_length=400)),
                ('warning', models.CharField(blank=True, max_length=300)),
                ('nutrition_facts', models.JSONField(blank=True, default=dict, help_text='100g of serving size', null=True)),
                ('ingredients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), blank=True, default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_active', 'index', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OtpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dial_code', models.CharField(max_length=3)),
                ('phone', models.CharField(max_length=15)),
                ('by', models.CharField(choices=[('kitchen', 'Kitchen'), ('customer', 'Customer'), ('courier', 'Courier')], max_length=15)),
                ('channel', models.CharField(choices=[('sms', 'SMS')], max_length=15)),
                ('otp', models.CharField(max_length=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_version_format', message="Version must be in the format 'X.Y.Z' or 'X.Y.Z+build_number'.", regex='^\\d+(\\.\\d+)*(\\+\\d+)?$')])),
                ('stage', models.CharField(choices=[('dev', 'Dev'), ('alpha', 'Alpha'), ('beta', 'Beta'), ('stable', 'Stable')], default='dev', max_length=10)),
                ('channels', multiselectfield.db.fields.MultiSelectField(choices=[('app-store', 'App store'), ('play-store', 'Play store'), ('shorebird', 'Shorebird')], default='shorebird', max_length=150)),
                ('min_version', models.CharField(blank=True, max_length=20, null=True)),
                ('changelog', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('index', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-is_active', 'index', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SectionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-is_active', 'index'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(db_index=True, max_length=32, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_branch_less', models.BooleanField()),
                ('age_check', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=common.models.service.Service.upload_logo)),
                ('image', models.ImageField(blank=True, null=True, upload_to=common.models.service.Service.upload_image)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['index', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('max_capacity', models.PositiveSmallIntegerField(default=10)),
            ],
            options={
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(db_index=True, max_length=25)),
                ('weight', models.PositiveIntegerField(help_text='Grams')),
                ('volume', models.PositiveIntegerField(help_text='cm3')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['item', 'index'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('detour_index', models.DecimalField(decimal_places=2, max_digits=4)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('coords', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('branch', 'Branch'), ('courier', 'Courier'), ('customer', 'Customer')], max_length=20)),
                ('os', models.CharField(choices=[('android', 'Android'), ('ios', 'IOS')], max_length=10)),
                ('bundle_id', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
            options={
                'unique_together': {('type', 'os', 'bundle_id')},
            },
        ),
        migrations.CreateModel(
            name='BranchStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('busy', 'Busy'), ('closed', 'Closed')], max_length=10)),
                ('reason', models.TextField(blank=True, help_text='Busy or closed reason', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='branch.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('index', models.PositiveSmallIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to=common.models.catalog.category.Category.upload_image)),
                ('is_active', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='common.category')),
            ],
            options={
                'ordering': ['supplier__name', '-is_active', 'parent__name', 'name'],
            },
        ),
    ]
