# Generated by Django 6.0.4 on 2026-04-16 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='NULL means platform category (stores), NOT NULL means supplier-specific (kitchens)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='merchant.supplier'),
        ),
        migrations.AddField(
            model_name='cityservice',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.city'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='common.country'),
        ),
        migrations.AddField(
            model_name='gateway',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='common.country'),
        ),
        migrations.AddField(
            model_name='gatewayrule',
            name='gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rules', to='common.gateway'),
        ),
        migrations.AddField(
            model_name='item',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='merchant.supplier'),
        ),
        migrations.AddField(
            model_name='release',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='releases', to='common.app'),
        ),
    ]
