# Generated by Django 6.0.4 on 2026-04-16 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sectioncategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_categories', to='common.category'),
        ),
        migrations.AddField(
            model_name='sectioncategory',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_categories', to='common.section'),
        ),
        migrations.AddField(
            model_name='item',
            name='types',
            field=models.ManyToManyField(related_name='items', to='common.service'),
        ),
        migrations.AddField(
            model_name='cityservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.service'),
        ),
        migrations.AddField(
            model_name='city',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='Non-retail services available in this city (parcel, events, taxi, etc.)', related_name='cities', through='common.CityService', to='common.service'),
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='common.service'),
        ),
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together={('start', 'end')},
        ),
        migrations.AddField(
            model_name='variant',
            name='alternatives',
            field=models.ManyToManyField(blank=True, to='common.variant'),
        ),
        migrations.AddField(
            model_name='variant',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='common.item'),
        ),
        migrations.AddField(
            model_name='zone',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='common.city'),
        ),
        migrations.AddField(
            model_name='zone',
            name='neighbors',
            field=models.ManyToManyField(blank=True, help_text='Each zone must have at leat one neighbour zone which is itself', to='common.zone'),
        ),
        migrations.AlterUniqueTogether(
            name='gateway',
            unique_together={('country', 'name', 'currency')},
        ),
        migrations.AddConstraint(
            model_name='gatewayrule',
            constraint=models.CheckConstraint(condition=models.Q(('min__lt', models.F('max'))), name='min_less_than_max'),
        ),
        migrations.AlterUniqueTogether(
            name='release',
            unique_together={('app', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='sectioncategory',
            unique_together={('section', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='cityservice',
            unique_together={('city', 'service')},
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('country', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'parent', 'supplier')},
        ),
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together={('item', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='zone',
            unique_together={('city', 'name')},
        ),
    ]
