# Generated by Django 6.0.4 on 2026-04-16 00:18

import django.contrib.postgres.fields
import django.db.models.deletion
import event.models.event
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start', models.TimeField()),
                ('duration', models.DurationField(blank=True, null=True)),
                ('end', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'start'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('used', 'Used')], default='active', max_length=20)),
                ('seat', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('standard', 'Standard'), ('v.i.p', 'VIP'), ('business', 'Business'), ('premium', 'Premium')], max_length=20)),
                ('location', models.CharField(blank=True, choices=[('floor', 'Floor'), ('mezzanine', 'Mezzanine'), ('balcony', 'Balcony'), ('suite', 'Suite')], max_length=20, null=True)),
                ('section', models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extras', models.JSONField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField()),
                ('sold', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-price'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('concert', 'Concert'), ('conference', 'Conference'), ('theater', 'Theater'), ('sport', 'Sport'), ('movies', 'Movies'), ('excursion', 'Excursion'), ('show', 'Show'), ('course', 'Course')], max_length=20)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('pop', 'Pop'), ('rock', 'Rock'), ('jazz', 'Jazz'), ('classical', 'Classical'), ('hip_hop', 'Hip Hop'), ('rnb', 'R&B'), ('electronic', 'Electronic'), ('country', 'Country'), ('reggae', 'Reggae'), ('football', 'Football')], max_length=50), blank=True, default=list)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to=event.models.event.Event.upload_image)),
                ('min_age', models.PositiveSmallIntegerField(choices=[(6, 6), (12, 12), (16, 16), (18, 18)], null=True)),
                ('warning', models.CharField(blank=True, max_length=255, null=True)),
                ('terms', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='common.city')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
