# Generated by Django 6.0.4 on 2026-04-16 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('customer', '0001_initial'),
        ('event', '0001_initial'),
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='events', to='merchant.merchant'),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='event.event'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='event.eventschedule'),
        ),
        migrations.AddField(
            model_name='ticketorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_orders', to='customer.customer'),
        ),
        migrations.AddField(
            model_name='ticketorder',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='event.eventschedule'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='event.ticketorder'),
        ),
        migrations.AddField(
            model_name='tickettier',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventschedule'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tickets', to='event.tickettier'),
        ),
        migrations.AddField(
            model_name='venue',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='common.city'),
        ),
        migrations.AddField(
            model_name='venue',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venues', to='event.venue'),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='event.venue'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='event.venue'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('schedule', 'seat'), name='unique_ticket_per_seat_schedule'),
        ),
        migrations.AlterUniqueTogether(
            name='eventschedule',
            unique_together={('event', 'venue', 'date', 'start')},
        ),
    ]
