# Generated by Django 6.0.4 on 2026-04-16 00:18

import affiche.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Campagn name', max_length=100, unique=True)),
                ('image', models.ImageField(upload_to=affiche.models.Affiche.upload_image)),
                ('index', models.PositiveSmallIntegerField(default=0)),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['city', 'index'],
            },
        ),
    ]
