# Generated by Django 6.0.4 on 2026-04-16 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affiche', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiche',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiches', to='common.city'),
        ),
        migrations.AlterUniqueTogether(
            name='affiche',
            unique_together={('city', 'name')},
        ),
    ]
