# Generated by Django 6.0.4 on 2026-04-16 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0002_initial'),
        ('courier', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_dial_code', models.CharField(blank=True, choices=[('243', '243')], max_length=10, null=True)),
                ('sender_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('sender_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('receiver_name', models.CharField(blank=True, max_length=255, null=True)),
                ('receiver_dial_code', models.CharField(blank=True, choices=[('243', '243')], max_length=10, null=True)),
                ('receiver_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('receiver_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('document', 'Document'), ('food', 'Food'), ('grocery', 'Grocery'), ('flower', 'Flower'), ('pharmacy', 'Pharmacy'), ('electronics', 'Electronics'), ('package', 'Package'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_fragile', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('picked-up', 'Picked up'), ('on-the-way', 'On the way'), ('in-custody', 'In Custody'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=20)),
                ('code', models.CharField(editable=False, max_length=10, null=True)),
                ('pin', models.CharField(editable=False, max_length=6, null=True)),
                ('pickup_lat', models.FloatField(blank=True, null=True)),
                ('pickup_lng', models.FloatField(blank=True, null=True)),
                ('pickup_address', models.CharField(blank=True, max_length=255, null=True)),
                ('pickup_landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('pickup_courier_instructions', models.CharField(blank=True, max_length=255, null=True)),
                ('dropoff_lat', models.FloatField(blank=True, null=True)),
                ('dropoff_lng', models.FloatField(blank=True, null=True)),
                ('dropoff_address', models.CharField(blank=True, max_length=255, null=True)),
                ('dropoff_landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('dropoff_courier_instructions', models.CharField(blank=True, max_length=255, null=True)),
                ('custody_lat', models.FloatField(blank=True, null=True)),
                ('custody_lng', models.FloatField(blank=True, null=True)),
                ('custody_address', models.CharField(blank=True, max_length=255)),
                ('custody_landmark', models.CharField(blank=True, max_length=255)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('pickup_slot_start', models.TimeField(blank=True, null=True)),
                ('pickup_slot_end', models.TimeField(blank=True, null=True)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('protection_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('currency', models.CharField(choices=[('cdf', 'CDF')], editable=False, max_length=3)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('pickedup_at', models.DateTimeField(blank=True, null=True)),
                ('custody_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.CharField(blank=True, choices=[('sender', 'Sender'), ('courier', 'Courier'), ('staff', 'Staff'), ('system', 'System')], max_length=20, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='branch.branch')),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcels', to='courier.courier')),
                ('custody_courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_parcels', to='courier.courier')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='customer.customer')),
            ],
            options={
                'ordering': ['-placed_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('pickup_date__isnull', True), ('pickup_slot_end__isnull', True), ('pickup_slot_start__isnull', True)), models.Q(('pickup_date__isnull', False), ('pickup_slot_end__isnull', False), ('pickup_slot_start__isnull', False)), _connector='OR'), name='schedule_pickup_all_or_none')],
            },
        ),
    ]
