# Generated by Django 6.0.4 on 2026-04-16 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0003_initial'),
        ('courier', '0001_initial'),
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courieroffer',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='courier.courier'),
        ),
        migrations.AddField(
            model_name='courieroffer',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
        migrations.AddField(
            model_name='couriershift',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='courier.courier'),
        ),
        migrations.AddField(
            model_name='couriershift',
            name='slots',
            field=models.ManyToManyField(related_name='shifts', to='common.slot'),
        ),
        migrations.AddField(
            model_name='couriershift',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='common.zone'),
        ),
        migrations.AddField(
            model_name='couriertoken',
            name='courier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='courier.courier', verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='couriershift',
            index=models.Index(fields=['courier', 'status'], name='courier_cou_courier_51c163_idx'),
        ),
        migrations.AddIndex(
            model_name='couriershift',
            index=models.Index(fields=['start', 'end'], name='courier_cou_start_8b4ce3_idx'),
        ),
    ]
