# Generated by Django 6.0.4 on 2026-04-16 00:18

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('dial_code', models.CharField(choices=[('243', '243')], max_length=3)),
                ('phone', models.CharField(max_length=10)),
                ('password', models.CharField(blank=True, max_length=128, verbose_name='password')),
                ('image', models.ImageField(blank=True, null=True, upload_to=user.models.User.upload_image)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ('name', 'last_name'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('email',), name='user_unique_email', violation_error_message='Email already taken'), models.UniqueConstraint(condition=models.Q(('dial_code__isnull', False), ('phone__isnull', False)), fields=('dial_code', 'phone'), name='user_unique_phone', violation_error_message='Phone number already taken!')],
            },
        ),
    ]
