# Generated by Django 6.0.4 on 2026-04-16 00:18

import branch.models.tag
import django.contrib.postgres.fields
import django.core.validators
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.SlugField(max_length=20, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(regex='^[a-z0-9_-]+$')])),
                ('phone', models.CharField(help_text='Support contact', max_length=15)),
                ('ttr', models.DurationField(verbose_name='TTR')),
                ('ept', models.DurationField(verbose_name='EPT')),
                ('status', models.CharField(choices=[('open', 'Open'), ('busy', 'Busy'), ('closed', 'Closed')], default='closed', max_length=15)),
                ('delay_duration', models.DurationField(blank=True, null=True, verbose_name='EPT delay')),
                ('delay_start', models.DateTimeField(blank=True, null=True)),
                ('delay_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('h3_res8', models.CharField(db_index=True, max_length=16, null=True)),
                ('address', models.CharField(max_length=255)),
                ('landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('pickup_instructions', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.DecimalField(decimal_places=1, default=100, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-is_active', 'city', 'supplier__name', 'label'),
            },
        ),
        migrations.CreateModel(
            name='BranchManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(help_text='e.g. alain@grocery.cd or marie@kitchen.ci', max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_-]+@[a-zA-Z0-9_-]+.(duka|kitchen|grocery|cellar|pharmacy|beauty)', 'Username must be like name@grocery.cd or name@kitchen.ci')])),
                ('code', models.CharField(blank=True, help_text='Auto-generated if not set. Admin code: 3 to 8 lowercase alphanumeric characters. Is secret and private', max_length=6, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(message='Code must be 3 to 8 lowercase alphanumeric characters.', regex='^[a-z0-9]+$')])),
                ('last_seen', models.DateTimeField(blank=True, help_text='API last login', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-last_seen', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='BranchManagerToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Key')),
                ('used_at', models.DateTimeField(auto_now=True)),
                ('device', models.CharField(default='unknown', editable=False, max_length=50)),
                ('fcm', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Manager Token',
                'verbose_name_plural': 'Manager Tokens',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BranchVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('stock', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('max_per_order', models.PositiveIntegerField(default=10)),
                ('popularity_score', models.FloatField(db_index=True, default=0)),
                ('trend_score', models.FloatField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-is_active', 'branch'],
            },
        ),
        migrations.CreateModel(
            name='BranchVariantDailySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('qty', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('asap', 'ASAP'), ('same_day', 'Same-day'), ('next_day', 'Next-day')], max_length=20, null=True)),
                ('base_dispatch_buffer', models.DurationField(blank=True, null=True)),
                ('max_dispatch_buffer', models.DurationField(blank=True, null=True)),
                ('extra_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cutoff_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekdays', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')]), help_text='Select multiple weekdays for this shift')),
                ('start', models.TimeField(help_text='Local Time')),
                ('end', models.TimeField(help_text='Local Time')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('branch', 'weekdays'),
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('type', models.CharField(choices=[('consign-in', 'Consign In'), ('customer-return', 'Customer Return'), ('production-in', 'Production In'), ('release', 'Release'), ('restock', 'Restock'), ('transfer-in', 'Transfer In'), ('consign-out', 'Consign Out'), ('damage', 'Damage'), ('donation', 'Donation'), ('loss', 'Loss'), ('reserve', 'Reserve'), ('sale', 'Sale'), ('sample', 'Sample'), ('transfer-out', 'Transfer Out'), ('adjustment', 'Adjustment'), ('rollup', 'Rollup')], max_length=15)),
                ('qty', models.SmallIntegerField()),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(max_length=25, unique=True)),
                ('age_check', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to=branch.models.tag.Tag.upload_image)),
                ('is_active', models.BooleanField(default=True, help_text='If enabled for filtering.')),
            ],
            options={
                'ordering': ['-is_active', 'index', 'name'],
            },
        ),
    ]
