# Generated by Django 6.0.4 on 2026-04-16 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0002_initial'),
        ('common', '0001_initial'),
        ('merchant', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='merchant.supplier'),
        ),
        migrations.AddField(
            model_name='branch',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='common.service'),
        ),
        migrations.AddField(
            model_name='branchmanager',
            name='branch',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='branchmanagertoken',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='branch.branchmanager', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='branchvariant',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_variants', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='branchvariant',
            name='supplier_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_variants', to='merchant.suppliervariant'),
        ),
        migrations.AddField(
            model_name='branchvariantdailysales',
            name='branch_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sales', to='branch.branchvariant'),
        ),
        migrations.AddField(
            model_name='deliverytype',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_types', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='featurebranch',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='featurebranch',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='branch.feature'),
        ),
        migrations.AddField(
            model_name='shift',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='branch_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stock_movements', to='branch.branchvariant'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order'),
        ),
    ]
