# Generated by Django 6.0.4 on 2026-04-16 00:18

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0003_initial'),
        ('common', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='common.service'),
        ),
        migrations.AddField(
            model_name='branch',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='branches', to='branch.tag'),
        ),
        migrations.AddIndex(
            model_name='branchvariant',
            index=models.Index(fields=['branch', 'is_active'], name='branch_bran_branch__793b17_idx'),
        ),
        migrations.AddIndex(
            model_name='branchvariant',
            index=models.Index(fields=['branch', '-popularity_score'], name='branch_bran_branch__a0be3f_idx'),
        ),
        migrations.AddIndex(
            model_name='branchvariant',
            index=models.Index(fields=['branch', '-trend_score'], name='branch_bran_branch__33a192_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='branchvariant',
            unique_together={('branch', 'supplier_variant')},
        ),
        migrations.AddIndex(
            model_name='branchvariantdailysales',
            index=models.Index(fields=['date'], name='branch_bran_date_e9b0d9_idx'),
        ),
        migrations.AddIndex(
            model_name='branchvariantdailysales',
            index=models.Index(fields=['branch_variant', 'date'], name='branch_bran_branch__e66bfb_idx'),
        ),
        migrations.AddConstraint(
            model_name='branchvariantdailysales',
            constraint=models.UniqueConstraint(fields=('branch_variant', 'date'), name='unique_branch_variant_per_day'),
        ),
        migrations.AlterUniqueTogether(
            name='deliverytype',
            unique_together={('branch', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='featurebranch',
            unique_together={('feature', 'branch')},
        ),
        migrations.AddIndex(
            model_name='shift',
            index=django.contrib.postgres.indexes.GinIndex(fields=['weekdays'], name='branch_shif_weekday_6fcc0b_gin'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['weekdays', 'start', 'end'], name='branch_shif_weekday_74bd5d_idx'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.CheckConstraint(condition=models.Q(('start__lt', models.F('end'))), name='start_before_end'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('type', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('city', 'supplier', 'type', 'label')},
        ),
    ]
