# Generated by Django 6.0.4 on 2026-04-16 00:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0002_initial'),
        ('courier', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('placed', 'Placed'), ('accepted', 'Accepted'), ('ready', 'Ready'), ('picked-up', 'Picked up'), ('on-the-way', 'On the way'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='placed', max_length=20)),
                ('ept', models.DurationField(help_text='In duration', verbose_name='EPT')),
                ('dropoff_lat', models.FloatField()),
                ('dropoff_lng', models.FloatField()),
                ('dropoff_address', models.CharField(editable=False, max_length=255)),
                ('dropoff_landmark', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('dropoff_courier_instructions', models.CharField(blank=True, max_length=255, null=True)),
                ('dropoff_date', models.DateField(blank=True, null=True)),
                ('dropoff_slot_start', models.TimeField(blank=True, null=True)),
                ('dropoff_slot_end', models.TimeField(blank=True, null=True)),
                ('is_prepaid', models.BooleanField(null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('small_order_fee', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('cash_rounding_fee', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('currency', models.CharField(choices=[('cdf', 'CDF')], editable=False, max_length=3)),
                ('code', models.CharField(editable=False, max_length=10, null=True)),
                ('pin', models.CharField(editable=False, max_length=6, null=True)),
                ('allow_substitution', models.BooleanField(default=True)),
                ('commission_type', models.CharField(choices=[('fixed', 'Fixed'), ('percent', 'Percent')], max_length=50, null=True)),
                ('commission_value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('pickedup_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='branch.branch')),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='courier.courier')),
                ('customer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customer.customer')),
                ('delivery_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='branch.deliverytype')),
            ],
            options={
                'ordering': ['-placed_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('removed', models.BooleanField(default=False)),
                ('name', models.CharField(editable=False, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('substitution', models.JSONField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branch.branchvariant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('dropoff_date__isnull', True), ('dropoff_slot_end__isnull', True), ('dropoff_slot_start__isnull', True)), models.Q(('dropoff_date__isnull', False), ('dropoff_slot_end__isnull', False), ('dropoff_slot_start__isnull', False)), _connector='OR'), name='order_schedule_dropoff_all_or_none'),
        ),
    ]
